services:
  sync-server:
    build: .
    restart: always
    container_name: syncwatch-server
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Configuration du sous-domaine
      - "traefik.http.routers.syncwatch-server.rule=Host(`syncwatch-server.beclay.fr`)"
      - "traefik.http.routers.syncwatch-server.entrypoints=websecure"
      - "traefik.http.routers.syncwatch-server.tls.certresolver=le"
      # Node.js / Express / Socket.IO écoute sur le port 3001
      - "traefik.http.services.syncwatch-server.loadbalancer.server.port=3001"

networks:
  web:
    external: true
